Module5 task1
htmlacademy-adaptive/1554867-sedona-21 pull request #11
Opened 2020-12-02 15:38 UTC by SonicFear96

2020-12-04 15:35 UTC, SonicFear96 commented on source/less/blocks/copyright.less
>  }
Расположил верно

2020-12-04 15:35 UTC, SonicFear96 commented on source/less/blocks/page-footer.less
> +}
Расположил верно

2020-12-04 15:36 UTC, SonicFear96 commented on source/less/blocks/search.less
> +  padding: 33px 28px 49px 28px;
Правки внесены

2020-12-04 15:37 UTC, SonicFear96 commented on source/less/blocks/search.less
>    text-decoration: none;
Внесены

2020-12-04 15:37 UTC, SonicFear96 commented on source/less/blocks/social.less
>  }
Внесены

2020-12-05 09:53 UTC, vovaborisenko requested changes
## соответствие с макетами почти достигнуто, молодец!!
- есть пару недочетов:
![](https://content.screencast.com/users/VovaBorisenko8286/folders/Snagit/media/083cb224-bd31-4ffa-8b1c-e64f0be60be7/12.05.2020-12.42.png)

- также в десктопной версии контент не должен расширятся больше чем 1200px.
вот пример, как должно быть при ширине окна браузера больше 1200px:
![](https://content.screencast.com/users/VovaBorisenko8286/folders/Snagit/media/6daade5c-97cb-4319-a11f-184128d0f18f/12.05.2020-12.49.png)

2020-12-05 10:12 UTC, vovaborisenko requested changes

2020-12-05 10:12 UTC, vovaborisenko commented on source/less/blocks/advantages.less
>    width: 100%;
неправильный порядок css свойств

2020-12-05 10:12 UTC, vovaborisenko commented on source/less/blocks/advantages.less
> +  }
в таких случаях используй min-height вместо height , чтобы правильно себя вели блоки при большем количестве текста

2020-12-05 10:12 UTC, vovaborisenko commented on source/less/blocks/page-main.less
>  }
в таких случаях используй min-height вместо height , чтобы правильно себя вели блоки при большем количестве текста

2020-12-05 10:12 UTC, vovaborisenko commented on source/less/blocks/search.less
> +  }
неправильный порядок css свойств

2020-12-05 10:12 UTC, vovaborisenko commented on source/less/blocks/search.less
> +  }
неправильный порядок css свойств

2020-12-05 10:12 UTC, vovaborisenko commented on source/less/blocks/site-list.less
> +    }
неправильный порядок css свойств

2020-12-05 10:12 UTC, vovaborisenko commented on source/less/blocks/site-list.less
> +    border-bottom: 1px solid @border-bottom-color;
здесь лучше не использовать фиксированную высоту, все нужно задать отступами

2020-12-05 14:23 UTC, SonicFear96 commented on source/less/blocks/advantage.less
> +}
заменил на min-height

2020-12-05 14:27 UTC, SonicFear96 commented on source/less/blocks/advantage.less
> +}
прописал размеры в html, в дальнейшем будет картинка меняться, как в 6-ом задании (в мобильном меньше SVG картинка)

2020-12-05 14:28 UTC, SonicFear96 commented on source/less/blocks/advantage.less
>    background-color: @basic-grey;
Заменил

2020-12-05 14:30 UTC, SonicFear96 commented on source/less/blocks/advantage.less
> +  }
Сделал как модификатор advantage__image

2020-12-05 14:30 UTC, SonicFear96 commented on source/less/blocks/advantages.less
> +  background-color: @basic-blue;
Поменял

2020-12-05 14:30 UTC, SonicFear96 commented on source/less/blocks/advantages.less
> +}
заменил

2020-12-05 14:31 UTC, SonicFear96 commented on source/less/blocks/advantages.less
>    width: 100%;
поменял

2020-12-05 14:31 UTC, SonicFear96 commented on source/less/blocks/advantages.less
> +  }
Заменил

2020-12-05 14:32 UTC, SonicFear96 commented on source/less/blocks/page-main.less
>  }
заменил

2020-12-05 14:32 UTC, SonicFear96 commented on source/less/blocks/search.less
> +  }
поменял

2020-12-05 14:32 UTC, SonicFear96 commented on source/less/blocks/search.less
> +  }
поменял

2020-12-05 14:33 UTC, SonicFear96 commented on source/less/blocks/site-list.less
> +    }
поменял

2020-12-05 14:37 UTC, SonicFear96 commented on source/less/blocks/site-list.less
> +    border-bottom: 1px solid @border-bottom-color;
отступами сделал

2020-12-06 07:09 UTC, vovaborisenko requested changes
### есть еще доработки, давай последний рывок над этой страницей!!!

![image](https://user-images.githubusercontent.com/30496847/101273935-081d3800-37ab-11eb-8deb-af9c25455d23.png)
![image](https://user-images.githubusercontent.com/30496847/101273951-2420d980-37ab-11eb-869b-8e9cf3429a0c.png)

2020-12-06 07:09 UTC, vovaborisenko commented on source/less/blocks/page-main.less
> +  padding: 14px 28px 22px 28px;
неправильный порядок css свойств

2020-12-06 07:09 UTC, vovaborisenko commented on source/less/blocks/page.less
> +  padding: 0;
неправильный порядок css свойств

2020-12-06 11:44 UTC, SonicFear96 commented on source/less/blocks/advantage.less
> +  }
поправил

2020-12-06 11:44 UTC, SonicFear96 commented on source/less/blocks/page-main.less
> +  padding: 14px 28px 22px 28px;
поправил

2020-12-06 11:45 UTC, SonicFear96 commented on source/less/blocks/page.less
> +  padding: 0;
поправил

2020-12-06 12:32 UTC, merged