Module3 task1
htmlacademy-adaptive/1554867-sedona-21 pull request #5
Opened 2020-11-22 20:41 UTC by SonicFear96

2020-11-23 16:18 UTC, vovaborisenko requested changes
- в этой ветке закоммичены изменения файлов `catalog.html` и `form.html`. Эти изменения нужно удалить, чтобы в будущем не было конфликтов.
- перед каждый коммитом нужно запускать тесты `npm run test` и если все проходит без ошибок, только после этого коммитить.
- все файлы блоков должны содержать ТОЛЬКО стили для данного блока и никакие другие блоки не могут быть в этом файле. и этот файл должен иметь название блока. Например: 
у тебя есть файл `footer.less` с содержимым:
```
.page-footer__wrapper {
  text-align: center;
}
.social__list {
  list-style: none;
  padding: 0;
}
.social__item {
  display: inline;
}
```
этот файл нужно разбить на два файла: `page-footer.less` и `social.less` 
с этой проблемой у тебя есть несколько файлов.

- и не забывай проходить тесты!!!

2020-11-23 16:18 UTC, vovaborisenko commented on source/index.html
> +              <li class="advantages__item advantage--sub-item advantage">
зачем добавлен модификатор `advantage--sub-item`?

2020-11-23 16:18 UTC, vovaborisenko commented on source/less/blocks/advantages.less
> +  }
это стили отдельного блока `advantage` их нужно вынести в отдельный файл. 
с остальными файлами такая же беда

2020-11-24 17:10 UTC, SonicFear96 commented on source/index.html
> +              <li class="advantages__item advantage--sub-item advantage">
модификатор задаёт особенности данным элементам на странице (отличается расположение от остальных)

2020-11-24 18:58 UTC, vovaborisenko reviewed
все отлично, молодец!!

2020-11-24 18:58 UTC, merged