Module3 task2
htmlacademy-adaptive/1554867-sedona-21 pull request #6
Opened 2020-11-24 20:18 UTC by SonicFear96

2020-11-25 16:23 UTC, vovaborisenko requested changes
Хорошо все сделано

есть замечания, нужно исправить.

- необходимо чтобы во всех html footer'ы имели одинаковую разметку (касается этого тега `<h2>#visitsedona</h2>`).
- для модификаторов, псевдоэлементов, псевдоклассов можно использовать вложенность.

2020-11-25 16:23 UTC, vovaborisenko commented on source/less/blocks/fieldset.less
> +}
для модификаторов можно использовать вложенность

2020-11-25 16:23 UTC, vovaborisenko commented on source/less/blocks/fieldset.less
> +}
это лишнее (из html тоже удали этот класс)
ширина не должна быть фиксированной
фоновый цвет нужно задать элементу `field__input`

2020-11-25 16:23 UTC, vovaborisenko commented on source/less/blocks/fieldset.less
> +}
эти стили нужно задать просто элементу `field__input`, и ему нужно указать явно `font-family`
(цвет нужно продублировать для `::placeholder`)

2020-11-25 16:23 UTC, vovaborisenko commented on source/form.html
> +            <button class="button button__form" type="submit">Отправить отзыв</button>
я думаю, что `button__form` ты хотел написать как модификатор. исправь или объясни почему здесь элемент

2020-11-25 16:23 UTC, vovaborisenko commented on source/less/blocks/filters.less
> +}
в этом файле могут быть только селекторы блоков элементов и модификаторов для `.filters`

для `button` нужно создать отдельный файл

2020-11-25 16:23 UTC, vovaborisenko commented on source/less/blocks/page-main.less
> +}
для `title` нужно создать отдельный файл

2020-11-25 18:51 UTC, SonicFear96 commented on source/form.html
> +            <button class="button button__form" type="submit">Отправить отзыв</button>
Сделал как оформлена button в index.html (там search__button)

2020-11-25 19:03 UTC, SonicFear96 commented on source/less/blocks/filters.less
> +}
Добавил

2020-11-25 19:03 UTC, SonicFear96 commented on source/less/blocks/page-main.less
> +}
Добавил

2020-11-25 19:06 UTC, SonicFear96 commented on source/less/blocks/fieldset.less
> +}
Указал для field__input, добавил вложенность и ::placeholder оставил цвет

2020-11-25 19:06 UTC, SonicFear96 commented on source/less/blocks/fieldset.less
> +}
фоновый задан

2020-11-25 19:06 UTC, SonicFear96 commented on source/less/blocks/fieldset.less
> +}
Вложенность использована

2020-11-26 04:03 UTC, vovaborisenko requested changes
# каждый `less` файл должен содержать селекторы ТОЛЬКО блока с таким же названием как и у файла!!!!!

2020-11-26 09:07 UTC, SonicFear96 commented on source/less/blocks/fieldset.less
> +}
Почему только сейчас сказали про блок field?

2020-11-26 09:08 UTC, SonicFear96 commented on source/less/blocks/button.less
> +}
Зачем попросили создать папку button, если надо было переименовать блок и оставить на своём месте?

2020-11-26 10:58 UTC, vovaborisenko commented on source/less/blocks/button.less
> +}
Потому что был другой селектор: button__form, который должен был быть в файле button.less

2020-11-26 10:58 UTC, vovaborisenko commented on source/less/blocks/fieldset.less
> +}
Потому что не заметил

2020-11-26 11:00 UTC, vovaborisenko reviewed
Все исправлено, молодец

2020-11-26 11:00 UTC, merged